// web/lib/nameValidation.ts

/** Returns an error message if the name fails format rules, otherwise null. */
export function validateNameFormat(name: string): string | null {
  const trimmed = name.trim();
  if (trimmed.length < 2) return "Name must be at least 2 characters";
  if (trimmed.length > 30) return "Name must be 30 characters or fewer";
  if (!/^[a-zA-Z0-9 \-'.]+$/.test(trimmed)) return "Only letters, numbers, spaces, - ' . are allowed";
  return null;
}

// Server-side only — not imported in client components
export const PROFANITY_LIST: readonly string[] = [
  // Sexual profanity
  "anal", "analannie", "analsex", "anus", "areola", "aroused",
  "arse", "arsehole", "ass", "assbagger", "assblaster", "assclown",
  "asscowboy", "asses", "assfuck", "assfucker", "asshat", "asshole",
  "assholes", "asshore", "assjockey", "asskiss", "asskisser", "assklown",
  "asslick", "asslicker", "asslover", "assman", "assmonkey", "assmunch",
  "assmuncher", "asspacker", "asspirate", "asspuppies", "assranger",
  "asswhore", "asswipe",
  "backdoorman", "balllicker", "balls", "ballsack", "barelylegal",
  "beastality", "beastial", "beastiality", "beatoff", "beatyourmeat",
  "beaver", "bestial", "bestiality", "biatch", "bitch", "bitcher",
  "bitches", "bitchez", "bitchin", "bitching", "bitchslap", "bitchy",
  "biteme", "blowjob", "bollick", "bollock", "bollocks", "bondage",
  "boner", "boob", "boobies", "boobs", "booby", "boody", "bootycall",
  "brea5t", "breast", "breastjob", "breastlover", "breastman", "brothel",
  "bugger", "buggered", "buggery", "bullshit", "bumblefuck", "bumfuck",
  "bunghole", "butchbabes", "butchdike", "butchdyke", "butt", "buttbang",
  "buttface", "buttfuck", "buttfucker", "buttfuckers", "butthead",
  "buttman", "buttmunch", "buttmuncher", "buttpirate", "buttplug", "buttstain",
  "cameltoe", "carpetmuncher", "cherrypopper", "chickslick", "clamdigger",
  "clamdiver", "clit", "clitoris", "cock", "cockblock", "cockblocker",
  "cockcowboy", "cockfight", "cockhead", "cockknob", "cocklicker",
  "cocklover", "cocknob", "cockqueen", "cockrider", "cocksman", "cocksmith",
  "cocksmoker", "cocksucer", "cocksuck", "cocksucked", "cocksucker",
  "cocksucking", "cocktease", "coitus", "condom", "coon", "coondog",
  "copulate", "cornhole", "crotch", "crotchjockey", "crotchmonkey", "crotchrot",
  "cum", "cumbubble", "cumfest", "cumjockey", "cumm", "cummer", "cumming",
  "cumquat", "cumqueen", "cumshot", "cunilingus", "cunillingus", "cunn",
  "cunnilingus", "cunntt", "cunt", "cunteyed", "cuntfuck", "cuntfucker",
  "cuntlick", "cuntlicker", "cuntlicking", "cuntsucker", "cybersex",
  "deapthroat", "deepthroat", "defecate", "dick", "dickbrain", "dickforbrains",
  "dickhead", "dickless", "dicklick", "dicklicker", "dickman", "dickwad",
  "dickweed", "diddle", "dildo", "dingleberry", "dipshit", "dixiedike",
  "dixiedyke", "doggiestyle", "doggystyle", "dong", "doodoo", "dripdick",
  "dumbass", "dumbbitch", "dumbfuck", "dyke",
  "easyslut", "eatballs", "eatme", "eatpussy", "ejaculate", "ejaculated",
  "ejaculating", "ejaculation", "enema", "erect", "erection",
  "facefucker", "faeces", "fag", "fagging", "faggot", "fagot",
  "fannyfucker", "fart", "farted", "farting", "farty", "fastfuck",
  "fatass", "fatfuck", "fatfucker", "fckcum", "feces", "felatio",
  "felch", "felcher", "felching", "fellatio", "feltch", "feltcher",
  "feltching", "fetish", "fingerfood", "fingerfuck", "fingerfucked",
  "fingerfucker", "fingerfuckers", "fingerfucking", "fister", "fistfuck",
  "fistfucked", "fistfucker", "fistfucking", "fisting", "flasher",
  "fondle", "footfuck", "footfucker", "footlicker", "foreskin", "fornicate",
  "foursome", "freakfuck", "freakyfucker", "freefuck",
  "fubar", "fuck", "fucka", "fuckable", "fuckbag", "fuckbuddy", "fucked",
  "fuckedup", "fucker", "fuckers", "fuckface", "fuckfest", "fuckfreak",
  "fuckfriend", "fuckhead", "fuckher", "fuckin", "fuckina", "fucking",
  "fuckingbitch", "fuckinnuts", "fuckinright", "fuckit", "fuckknob",
  "fuckme", "fuckmehard", "fuckmonkey", "fuckoff", "fuckpig", "fucks",
  "fucktard", "fuckwhore", "fuckyou", "fudgepacker", "fuk", "fuks", "fuuck",
  "gangbang", "gangbanged", "gangbanger", "gaymuthafuckinwhore", "gaysex",
  "genital", "givehead", "glazeddonut", "goldenshower", "gonorrehea",
  "handjob", "hardon", "headfuck", "herpes", "hiscock", "ho",
  "holestuffer", "homo", "homobangers", "homosexual", "hooker", "hookers",
  "hooters", "hore", "horniest", "horny", "horseshit", "hosejob",
  "hotpussy", "hottotrot", "hummer", "hustler", "hymen",
  "incest", "insest", "intercourse", "intheass", "inthebuff",
  "jackass", "jackoff", "jackshit", "jerkoff", "jism", "jiz", "jizim",
  "jizjuice", "jizm", "jizz", "jizzim", "jizzum", "jugs", "junglebunny",
  "kink", "kinky", "kissass", "kock", "kum", "kumbubble", "kumbullbe",
  "kummer", "kumming", "kumquat", "kums", "kunilingus", "kunnilingus", "kunt",
  "lactate", "laid", "lapdance", "lesbain", "lesbayn", "lesbian", "lesbin",
  "lesbo", "lez", "lezbe", "lezbefriends", "lezbo", "lezz", "lezzo",
  "libido", "lickme", "limpdick", "livesex", "lolita", "lubejob",
  "luckycammeltoe", "lynch",
  "manhater", "manpaste", "mastabate", "mastabater", "masterbate",
  "masterblaster", "mastrabator", "masturbate", "masturbating",
  "mattressprincess", "meatbeatter", "meatrack", "milf", "muff", "muffdive",
  "muffdiver", "muffindiver", "mufflikcer",
  "naked", "nasty", "nastybitch", "nastyho", "nastyslut", "nastywhore",
  "necro", "nofuckingway", "nookie", "nude", "nutfucker", "nymph",
  "ontherag", "orgasim", "orgasm", "orgies", "orgy",
  "pansies", "pansy", "pearlnecklace", "pecker", "pee", "peehole",
  "peepshow", "penetration", "peni5", "penile", "penis", "penises",
  "perv", "phonesex", "phuk", "phuked", "phuking", "phukked", "phukking",
  "phungky", "phuq", "pi55", "pimp", "pimped", "pimper", "pimpjuic",
  "pimpjuice", "pimpsimp", "pindick", "piss", "pissed", "pisser",
  "pisses", "pisshead", "pissin", "pissing", "pissoff", "pocketpool",
  "poo", "poon", "poontang", "poop", "pooper", "pooperscooper", "pooping",
  "popimp", "porn", "pornflick", "pornking", "porno", "pornography",
  "pornprincess", "premature", "pric", "prick", "prickhead",
  "prostitute", "pu55i", "pu55y", "pubic", "pubiclice", "pud", "pudboy",
  "pudd", "puddboy", "puke", "puntang", "purinapricness", "puss", "pussie",
  "pussies", "pussy", "pussycat", "pussyeater", "pussyfucker", "pussylicker",
  "pussylips", "pussylover", "pussypounder", "pusy",
  "queef", "queer", "quickie", "quim",
  "rape", "raped", "raper", "rapist", "rearend", "rearentry", "rectum",
  "redlight", "rentafuck", "retard", "retarded", "ribbed", "rimjob",
  "rimming", "rump",
  "sadom", "sandm", "scrotum", "semen", "sex", "sexed", "sexfarm",
  "sexhound", "sexhouse", "sexing", "sexkitten", "sexpot", "sexslave",
  "sextogo", "sextoy", "sextoys", "sexual", "sexually", "sexwhore",
  "sexymoma", "shag", "shaggin", "shagging", "shat", "sheeney", "shhit",
  "shit", "shitcan", "shitdick", "shite", "shiteater", "shited", "shitface",
  "shitfaced", "shitfit", "shitforbrains", "shitfuck", "shitfucker",
  "shitfull", "shithapens", "shithappens", "shithead", "shithouse", "shiting",
  "shitlist", "shitola", "shitoutofluck", "shits", "shitstain", "shitted",
  "shitter", "shitting", "shitty", "shortfuck", "sissy", "sixtynine",
  "sixtyniner", "skank", "skankbitch", "skankfuck", "skankwhore", "skanky",
  "skankybitch", "skankywhore", "skinflute", "skum", "skumbag", "slapper",
  "slideitin", "slime", "slimeball", "slimebucket", "slut", "sluts",
  "slutt", "slutting", "slutty", "slutwear", "slutwhore", "smackthemonkey",
  "smut", "snatch", "snatchpatch", "sodom", "sodomise", "sodomite",
  "sodomize", "sodomy", "sonofabitch", "sonofbitch", "spank",
  "spankthemonkey", "sperm", "spermacide", "spermbag", "spermhearder",
  "spermherder", "spit", "splittail", "spooge", "spreadeagle", "spunk",
  "spunky", "strapon", "stroke", "stroking", "stupidfuck", "stupidfucker",
  "suck", "suckdick", "sucker", "suckme", "suckmyass", "suckmydick",
  "suckmytit", "suckoff", "swallow", "swallower", "swalow", "syphilis",
  "taboo", "tampon", "tarbaby", "teat", "teste", "testicle", "testicles",
  "threesome", "threeway", "tinkle", "tit", "titbitnipply", "titfuck",
  "titfucker", "titfuckin", "titjob", "titlicker", "titlover", "tits",
  "tittie", "titties", "titty", "toilet", "tongethruster", "tonguethrust",
  "tonguetramp", "tosser", "tramp", "trannie", "tranny", "transexual",
  "transsexual", "transvestite", "trisexual", "turd", "twat", "twink",
  "twobitwhore", "unfuckable", "upskirt", "uptheass", "upthebutt",
  "urinate", "urine",
  "vagina", "vaginal", "vibr", "vibrater", "vibrator", "vomit", "vulva",
  "wank", "wanker", "wanking", "weenie", "weewee", "wetspot", "whacker",
  "whore", "whorefucker", "whorehouse", "willie", "williewanker", "willy",
  "xxx",

  // Racial slurs & hate speech
  "abbo", "abo", "alligatorbait", "argie",
  "beaner", "bohunk", "boang", "bogan", "boong", "boonga", "boonie",
  "bountybar", "bulldike", "bulldyke",
  "cameljockey", "chav", "chin", "chinaman", "chinamen", "chink", "chinky",
  "clogwog", "cohee", "coolie", "cooly", "coon",
  "dago", "darkie", "darky", "datnigga",
  "flipflop", "gatorbait", "ginzo", "gipp", "gook", "greaseball", "gringo",
  "gubba", "gyp", "gypo", "gypp", "gyppie", "gyppo", "gyppy",
  "hapa", "hebe", "heeb", "hindoo", "hitlerism", "hitlerist", "hodgie",
  "honger", "honkey", "honky",
  "ikey",
  "jap", "japcrap", "jiga", "jigaboo", "jigg", "jigga", "jiggabo",
  "jigger", "jiggy", "jijjiboo", "jimfish",
  "kaffer", "kaffir", "kaffre", "kafir", "kanake", "kigger", "kike",
  "kkk", "koon", "kraut", "kyke",
  "limey", "limy", "lugan",
  "macaca", "mgger", "mggor", "moky", "mockey", "mockie", "mocky",
  "mooncricket", "mulatto", "munt",
  "nazi", "negro", "negroes", "negroid", "nig", "nigg", "nigga", "niggah",
  "niggaracci", "niggaz", "nigger", "niggerhead", "niggerhole", "niggers",
  "niggor", "niggur", "niglet", "nignog", "nigr", "nigra", "nigre",
  "nip", "nlgger", "nlggor",
  "paki", "palesimian", "peckerwood", "picaninny", "piccaninny",
  "pickaninny", "piker", "pikey", "piky", "pohm", "polack", "pom",
  "pommie", "pommy", "poorwhitetrash", "porchmonkey",
  "ra8s", "raghead", "redneck", "reestie", "rigger", "roundeye", "russki", "russkie",
  "samckdaddy", "sandnigger", "scallywag", "seppo", "shav", "shinola",
  "slant", "slanteye", "slav", "slopehead", "slopey", "slopy",
  "snigger", "sniggered", "sniggering", "sniggers", "snowback", "snownigger",
  "sooty", "spaghettibender", "spaghettinigger", "spic", "spick", "spig",
  "spigotty", "spik", "squaw",
  "taff", "timbernigger", "towelhead", "trailertrash",
  "vietcong",
  "wab", "welcher", "wetback", "whigger", "whitenigger", "whitetrash",
  "wigger", "wog", "wop",
  "yellowman",
  "zigabo", "zipperhead",

  // Other hate / extremism
  "hitler", "pedophile", "pedo", "nonce",
];

// Pre-compiled for performance — rebuilt once at module load
const PROFANITY_REGEX = new RegExp(
  `\\b(${PROFANITY_LIST.join("|")})\\b`,
  "i"
);

/** Returns true if the name contains a profanity word (whole-word, case-insensitive). */
export function containsProfanity(name: string): boolean {
  return PROFANITY_REGEX.test(name);
}
